# Workflow to demonstrate docker is running

name: docker is running demo

on:
  workflow_dispatch:
    inputs:
      endpoint:
        description: 'endpoint to test'
        default: 'welcome'
        required: true

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Java JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11.0.10'
        java-package: jdk
        architecture: x64
    - name: build jar
      run: ./mvnw clean package
    - name: build docker image
      run: docker build -t springio/api-assignment .
    - name: run container
      run: docker run -d -p 80:8080 springio/api-assignment
    - name: check if container is running
      run: if [ $(docker inspect -f '{{.State.Running}}' test) = "true" ]; then echo "container's running"; else echo "it's not running"; fi
